import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'th' | 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getFontClass: () => string;
  formatCurrency: (amount: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Logout',
    
    // Authentication
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.forgotPassword': 'Forgot Password',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.phoneNumber': 'Phone Number',
    'auth.title': 'Title',
    'auth.selectTitle': 'Select title',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.nextChildrenInfo': 'Next: Children Information',
    'auth.rememberMe': 'Remember me',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',
    'auth.signUpHere': 'Sign up here',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordTitle': 'Reset Password',
    'auth.resetPasswordSubtitle': 'Please enter your registered email to receive the password reset link.',
    'auth.backToLogin': 'Back to Login',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.emailSent': 'Email Sent',
    'auth.emailSentMessage': 'An email with instructions to reset your password has been sent to',
    'auth.checkInboxMessage': 'Please check your inbox, if you do not receive the email within a few minutes, please check your spam or junk folder.',
    'auth.orContinueWith': 'Or continue with',
    'auth.continue': 'Continue',
    'auth.sendingOTP': 'Sending OTP...',
    'auth.verifyOTP': 'Verify OTP',
    'auth.otpSubtitle': 'Enter the verification code sent to your email',
    'auth.otpSentTo': 'OTP code has been sent to',
    'auth.enterOTP': 'Enter OTP Code',
    'auth.verify': 'Verify',
    'auth.verifying': 'Verifying...',
    'auth.didntReceiveOTP': "Didn't receive the code?",
    'auth.resendOTP': 'Resend OTP',
    'auth.resendOTPIn': 'Resend in',
    'auth.changeEmail': 'Change Email',
    'auth.otpResent': 'OTP Resent',
    'auth.otpResentMessage': 'A new OTP code has been sent to your email',
    'auth.emailPlaceholder': 'Enter your email address',
    // Error messages
    'auth.errors.emailRequired': 'Email or phone number is required',
    'auth.errors.passwordMin': 'Password must be at least 6 characters',
    'auth.errors.emailInvalid': 'Please enter a valid email address',
    'auth.errors.otpInvalid': 'Please enter a valid 6-digit OTP code',
    'auth.errors.titleRequired': 'Title is required',
    'auth.errors.firstNameRequired': 'First name is required',
    'auth.errors.lastNameRequired': 'Last name is required',
    'auth.errors.phoneRequired': 'Phone number is required',
    'auth.errors.passwordRequired': 'Password is required',
    'auth.errors.passwordConfirmRequired': 'Please confirm your password',
    'auth.errors.passwordMismatch': 'Passwords do not match',
    'auth.errors.emailMismatch': 'Emails do not match',
    'auth.errors.agreeTermsRequired': 'You must agree to the terms and conditions',
    'auth.errors.agreePDPARequired': 'You must agree to the privacy policy',
    'auth.errors.passportIdRequired': 'ID/Passport number is required',
    'auth.errors.nicknameRequired': 'Nickname is required',
    // Dropdown options
    'auth.titles.mr': 'Mr.',
    'auth.titles.mrs': 'Mrs.',
    'auth.titles.ms': 'Ms.',
    'auth.titles.dr': 'Dr.',
    'auth.titles.prof': 'Prof.',
    'auth.grades.kindergarten': 'Kindergarten',
    'auth.grades.grade1': 'Grade 1',
    'auth.grades.grade2': 'Grade 2',
    'auth.grades.grade3': 'Grade 3',
    'auth.grades.grade4': 'Grade 4',
    'auth.grades.grade5': 'Grade 5',
    'auth.grades.grade6': 'Grade 6',
    'auth.grades.grade7': 'Grade 7',
    'auth.grades.grade8': 'Grade 8',
    'auth.grades.grade9': 'Grade 9',
    'auth.grades.grade10': 'Grade 10',
    'auth.grades.grade11': 'Grade 11',
    'auth.grades.grade12': 'Grade 12',
    'auth.acceptTerms': 'I accept the',
    'auth.and': 'and',
    'auth.termsOfService': 'Terms of Service',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.signupTitle': 'Sign Up',
    'auth.signupSubtitle': 'Get started in just a few steps',
    'auth.step1': 'Parent Information',
    'auth.step2': 'Children Information',
    'auth.addChild': 'Add Child',
    'auth.child': 'Child',
    'auth.grade': 'Grade',
    'auth.selectGrade': 'Select grade',
    'auth.campus': 'Campus',
    'auth.selectCampus': 'Select campus',
    'auth.passportId': 'ID/Passport Number',
    'auth.passportIdPlaceholder': 'Enter ID or passport number',
    'auth.confirmEmail': 'Confirm Email',
    'auth.confirmEmailPlaceholder': 'Re-enter your email address',
    'auth.wechatLineId': 'WeChat/Line ID (Optional)',
    'auth.wechatLineIdPlaceholder': 'Enter WeChat ID or Line ID',
    'auth.agentName': 'Agent Name (If any)',
    'auth.agentNamePlaceholder': 'Enter agent name',
    'auth.nickname': 'Nickname',
    'auth.nicknamePlaceholder': 'Enter nickname',
    
    // Portal
    'portal.title': 'Parent Portal',
    'portal.welcome': 'Welcome',
    'portal.loginTitle': 'Log in',
    'portal.loginSubtitle': 'Welcome to parent portal',
    'portal.today': 'Today',
    'portal.notifications': 'Notifications',
    'portal.tuitionPayment': 'Tuition Payment',
    'portal.extraActivities': 'Extra Activities',
    'portal.others': 'Others',
    'portal.selectStudent': 'Select Student',
    'portal.viewAllChildren': 'View all Children',
    'portal.dashboard': 'Dashboard',
    'portal.tuition': 'Tuition',
    'portal.afterSchool': 'After School',
    'portal.summer': 'Camp',
    'portal.receipts': 'Receipts',
    'portal.outstandingInvoices': 'Outstanding Invoices',
    'portal.paidThisTerm': 'Paid This Term',
    'portal.creditBalance': 'Credit Balance',
    'portal.availableCourses': 'Available Courses',
    'portal.upcomingDeadlines': 'Upcoming Deadlines',
    'portal.importantDates': 'Important dates and reminders for',
    'portal.pending': 'pending',
    'portal.completedPayments': 'Completed payments',
    'portal.availableCredit': 'Available credit',
    'portal.coursesWithSpots': 'Courses with spots',
    'portal.due': 'Due',
    'portal.cart': 'Cart',
     'portal.items': 'items',
    'portal.itemsSelected': 'items selected',
    'portal.priceDetails': 'Price Details',
    'portal.total': 'Total',
    'portal.cartStep': 'Cart',
    'portal.paymentStep': 'Payment',
    'portal.receiveStep': 'Complete',
    'portal.backToDashboard': 'Back to Dashboard',
     'portal.proceedToCheckout': 'Proceed to Checkout',
     'portal.cartEmpty': 'Your cart is empty',
     'portal.backToActivities': 'Back to Activities',
     'portal.subtotal': 'Subtotal',
     'portal.parentAccount': 'Parent Account',
     'portal.accountSettings': 'Account Settings',
     'portal.paymentMethods': 'Payment Methods',
     'portal.notificationSettings': 'Notification Settings',
     'portal.allStudents': 'All Students',
     'portal.studentFilter': 'Filter by Student',
     'portal.addItemsToCart': 'Add some courses or activities to get started',
     'portal.selectAll': 'Select All',
     'portal.selectedItems': 'Selected Items',
     'portal.course': 'Course',
     'portal.noReceipts': 'No receipts available',
     'portal.downloadReceipt': 'Download receipt',
     'portal.courseSelected': 'Course selected for enrollment',
     'portal.activity': 'Activity',
     'portal.addedToCart': 'Added to Cart',
     'portal.removedFromCart': 'Removed from Cart',
     'portal.tuitionFees': 'Tuition Fees',
     'portal.checkout': 'Checkout',
     'portal.vendor': 'Vendor',
     'portal.tuitionStatus': 'Tuition Status',
     'portal.afterSchoolActivities': 'After School Activities',
     'portal.summerActivities': 'Camp Activities',
     'portal.academicYear': 'Academic Year 2024-2025',
     'portal.paid': 'Paid',
     'portal.pendingStatus': 'Pending',
     'portal.noInvoice': 'No Invoice',
     'portal.enrolled': 'Enrolled',
     'portal.noAfterSchoolEnrolled': 'No after school activities enrolled',
     'portal.noSummerEnrolled': 'No camp activities enrolled',
     'portal.fullyBooked': 'Fully Booked',
     'portal.spotsLeft': 'spots left',
     'portal.spotsAvailable': 'spots available',
     'portal.capacity': 'Capacity',
     'portal.scheduleConflict': 'Schedule conflict with existing courses',
     'portal.addToCart': 'Add to Cart',
     'portal.removeFromCart': 'Remove from Cart',
     'portal.receiptName': 'Receipt Name',
     'portal.dateOfPurchase': 'Date of Purchase',
     'portal.amount': 'Amount',
     'portal.category': 'Category',
      'portal.student': 'Student',
      
      // Cart
      'cart.timeRemaining': 'Time remaining',
     
     // Course translations
     'course.course-001.name': 'Robotics Engineering',
     'course.course-001.description': 'Learn robotics and engineering fundamentals',
     'course.course-002.name': 'Advanced Mathematics',
     'course.course-002.description': 'Excel in complex mathematical concepts',
     'course.course-003.name': 'Creative Writing',
     'course.course-003.description': 'Express creativity through storytelling and poetry',
     'course.course-004.name': 'Foreign Language (Spanish)',
     'course.course-004.description': 'Master Spanish language communication skills',
     'course.course-005.name': 'Art & Design',
     'course.course-005.description': 'Explore artistic expression through various mediums',
     'course.summer-001.name': 'Robotics & Engineering Camp',
     'course.summer-001.description': 'Hands-on STEM learning experience',
     'course.summer-002.name': 'Art & Craft Workshop',
     'course.summer-002.description': 'Express creativity through various art mediums',
      'course.summer-003.name': 'Soccer Skills Academy',
      'course.summer-003.description': 'Improve soccer techniques and teamwork',
     
     // Payment methods
     'payment.creditCard': 'Credit Card',
     'payment.bankTransfer': 'Bank Transfer',
     'payment.creditNote': 'Credit Note',
     'payment.cash': 'Cash',
     'payment.promptPay': 'PromptPay', 
     'payment.wechatPay': 'WeChat Pay',
     'payment.alipay': 'Alipay',
     'payment.bankAccount': 'Bank Account',
    // Portal - Payment
    'portal.paymentOptions': 'Payment Options',
    'portal.paymentPeriod': 'Payment Period',
    'portal.termly': 'Termly',
    'portal.yearly': 'Yearly (Save 10%)',
    'portal.applyCreditNote': 'Apply Credit Note',
    'portal.useCreditNote': 'Use Credit Note',
    'portal.available': 'Available',
    'portal.paymentMethod': 'Payment Method',
    'portal.free': 'Free',
    'portal.paymentSummary': 'Payment Summary',
    'portal.tuitionFee': 'Tuition Fee',
    'portal.creditNoteApplied': 'Credit Note Applied',
    'portal.paymentFee': 'Payment Fee',
    'portal.totalAmount': 'Total Amount',
    'portal.cancel': 'Cancel',
    'portal.pay': 'Pay',
    'portal.payNow': 'Pay',
    'portal.applyCreditPay': 'Apply Credit & Pay',
    
    // Invoice Status
    'invoice.pending': 'Pending',
    'invoice.overdue': 'Overdue',
    'invoice.paid': 'Paid',
    'invoice.partial': 'Partial',
    'invoice.due': 'Due',
    'invoice.amountDue': 'Amount Due',
    'invoice.availableCredit': 'Available Credit',
    'invoice.canPayWithCredit': 'Can be paid with available credit',
    
    // Payment Success
    'payment.success': 'Payment Successful',
    'payment.successMessage': 'Payment for {studentName} has been completed successfully',
    'payment.paymentDetails': 'Payment Details',
    'payment.receiptNumber': 'Receipt Number',
    'payment.amount': 'Amount',
    'payment.paymentDate': 'Payment Date',
    'payment.paymentMethod': 'Payment Method',
    'payment.paymentType': 'Payment Type',
    'payment.downloadReceipt': 'Download Receipt PDF',
    'payment.downloadStarted': 'Receipt PDF download will begin shortly',
    'payment.backToMain': 'Back to Main',
    'payment.emailNotification': 'Receipt will be sent to your registered email within 5-10 minutes',
    
    // Progress
    'progress.cart': 'Cart',
    'progress.payment': 'Payment',
    'progress.success': 'Complete',
    
    // Payment Processing
    'processing.selectPayment': 'Select Payment Method',
    'processing.confirmPayment': 'Confirm Payment',
    'processing.processing': 'Processing...',
    'processing.success': 'Payment Successful!',
    'processing.failed': 'Payment Failed',
    'processing.timeout': 'Payment timeout. Please try again.',
    'processing.scanQR': 'Scan QR Code to Pay',
    'processing.timeRemaining': 'Time remaining',
    'processing.bankDetails': 'Bank Account Details',
    'processing.accountNumber': 'Account Number',
    'processing.accountName': 'Account Name',
    'processing.bank': 'Bank',
    'processing.amount': 'Amount',
    'processing.back': 'Back',
    'processing.tryAgain': 'Try Again',
    'processing.cancel': 'Cancel',
    'processing.redirecting': 'Redirecting to bank...',
    'processing.checkingPayment': 'Checking payment...',
    'processing.generatingReceipt': 'Generating receipt...',
    
    // Payment Success
    'success.paymentComplete': 'Payment Successful',
    'success.registrationComplete': 'Registration completed for',
    'success.activitiesRegistered': 'Registered Activities',
    'success.paymentDetails': 'Payment Details',
    'success.receiptNumber': 'Receipt Number',
    'success.paymentAmount': 'Amount',
    'success.paymentDate': 'Payment Date',
    'success.paymentMethod': 'Payment Method',
    'success.downloadPDF': 'Download Receipt PDF',
    'success.backToMain': 'Back to Main',
    'success.emailConfirmation': 'Receipt and registration details will be sent to your registered email within 5-10 minutes',
    
    // Common
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.step': 'Step',
    'common.of': 'of',
    
    // Days
    'day.monday': 'Monday',
    'day.tuesday': 'Tuesday',
    'day.wednesday': 'Wednesday',
    'day.thursday': 'Thursday',
    'day.friday': 'Friday',
    'day.saturday': 'Saturday',
    'day.sunday': 'Sunday',
    
    // Months
    'month.january': 'January',
    'month.february': 'February',
    'month.march': 'March',
    'month.april': 'April',
    'month.may': 'May',
    'month.june': 'June',
    'month.july': 'July',
    'month.august': 'August',
    'month.september': 'September',
    'month.october': 'October',
    'month.november': 'November',
    'month.december': 'December',
    
    // Exam
    'portal.exam': 'Exam',
    'exam.registration': 'Exam Registration',
    'exam.register': 'Register',
    'exam.registered': 'Exam registered',
    'exam.passportId': 'Passport/ID Number',
    'exam.passportIdPlaceholder': 'Enter passport or ID number',
    'exam.photoUpload': 'Photo',
    'exam.clickToUpload': 'Click to upload photo',
    'exam.grade': 'Grade',
    'exam.selectGrade': 'Select grade',
    'exam.gender': 'Gender',
    'exam.male': 'Male',
    'exam.female': 'Female',
    'exam.age': 'Age',
    'exam.agePlaceholder': 'Enter age',
    'exam.selectOption': 'Select Exam Option',
    'exam.examOnly': 'Exam Only',
    'exam.examWithDelivery': 'Exam + Results Delivery',
    'exam.deliveryOption': 'Results delivery',
    'exam.errors.passportRequired': 'Passport/ID number is required',
    'exam.errors.photoRequired': 'Photo is required',
    'exam.errors.gradeRequired': 'Grade is required',
    'exam.errors.genderRequired': 'Gender is required',
    'exam.errors.ageRequired': 'Valid age is required (1-25)',
    
    // Transaction History & Credit Note
    'portal.transactionHistory': 'Transaction History',
    'creditNote.title': 'Credit Note',
    'creditNote.history': 'Credit Note History',
    'creditNote.availableCredit': 'Available Credit',
    'creditNote.usedCredit': 'Used Credit',
    'creditNote.perStudentNote': 'Credit notes are per student and cannot be used across different students',
    'creditNote.filters': 'Filters',
    'creditNote.searchPlaceholder': 'Search Credit Note (ID, details)...',
    'creditNote.academicYear': 'Academic Year',
    'creditNote.allYears': 'All Years',
    'creditNote.type': 'Type',
    'creditNote.allTypes': 'All',
    'creditNote.active': 'Active',
    'creditNote.used': 'Used',
    'creditNote.expired': 'Expired',
    'creditNote.issued': 'Issued',
    'creditNote.noResults': 'No credit notes found',
    'creditNote.typeRefund': 'Refund',
    'creditNote.typeDiscount': 'Discount',
    'creditNote.typeOverpayment': 'Overpayment',
    'creditNote.typeCancellation': 'Cancellation',
    
    // Receipt filters and timeline
    'receipt.month': 'Month',
    'receipt.pickMonth': 'Pick a month',
    'receipt.clearMonth': 'Clear',
    'receipt.student': 'Student',
    'receipt.allStudents': 'All Students',
    'receipt.type': 'Type',
    'receipt.allTypes': 'All Types',
    'receipt.typeTuition': 'Tuition',
    'receipt.typeActivity': 'Activity',
    'receipt.typeCamp': 'Camp',
    'receipt.typeEvent': 'Event',
    'receipt.typeExam': 'Exam',
    'receipt.showing': 'Showing',
    'receipt.of': 'of',
    'receipt.transactionTimeline': 'Transaction Timeline',
    'receipt.usedCreditNote': 'Used Credit Note',
    'receipt.appliedTo': 'Applied to',
    'receipt.noCreditNotesUsed': 'No credit notes used in this transaction',
    
    // Event submenu
    'portal.eventExam': 'Exam',
    'portal.eventTrip': 'Trip',
    'portal.eventCarnival': 'Carnivals & Concerts',
    
    // Trip
    'trip.acceptTrip': 'Accept Trip',
    'trip.declineTrip': 'Decline Trip',
    'trip.proceedToPayment': 'Proceed to Payment',
    'trip.changeDecision': 'Change My Decision',
    'trip.notAttending': 'Not Attending',
    'trip.accepted': 'Accepted',
    'trip.paid': 'Paid',
    'trip.paymentDeadline': 'Payment Deadline',
    'trip.tripDetails': 'Trip Details',
    'trip.deadlinePassed': 'Deadline Passed',
    'trip.paymentConfirmed': 'Payment Confirmed',
    'trip.searchTrips': 'Search trips...',
    'trip.noTripsFound': 'No trips found',
    
    // Carnival
    'carnival.comingSoon': 'Coming Soon',
    'carnival.stayTuned': 'Stay tuned for upcoming events',
  },
  th: {
    // Navigation
    'nav.home': 'หน้าหลัก',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.services': 'บริการ',
    'nav.contact': 'ติดต่อ',
    'nav.login': 'เข้าสู่ระบบ',
    'nav.signup': 'สมัครสมาชิก',
    'nav.logout': 'ออกจากระบบ',
    
    // Authentication
    'auth.login': 'เข้าสู่ระบบ',
    'auth.signup': 'สมัครสมาชิก',
    'auth.forgotPassword': 'ลืมรหัสผ่าน',
    'auth.email': 'อีเมล',
    'auth.password': 'รหัสผ่าน',
    'auth.confirmPassword': 'ยืนยันรหัสผ่าน',
    'auth.fullName': 'ชื่อ-นามสกุล',
    'auth.phoneNumber': 'เบอร์โทรศัพท์',
    'auth.title': 'คำนำหน้า',
    'auth.selectTitle': 'เลือกคำนำหน้า',
    'auth.firstName': 'ชื่อ',
    'auth.lastName': 'นามสกุล',
    'auth.nextChildrenInfo': 'ถัดไป: ข้อมูลบุตร',
    'auth.rememberMe': 'จดจำการเข้าสู่ระบบ',
    'auth.noAccount': 'ยังไม่มีบัญชี?',
    'auth.hasAccount': 'มีบัญชีแล้ว?',
    'auth.signInHere': 'เข้าสู่ระบบที่นี่',
    'auth.signUpHere': 'สมัครสมาชิกที่นี่',
    'auth.resetPassword': 'รีเซ็ตรหัสผ่าน',
    'auth.resetPasswordTitle': 'รีเซ็ตรหัสผ่าน',
    'auth.resetPasswordSubtitle': 'กรุณากรอกอีเมลที่ลงทะเบียนไว้เพื่อรับลิงก์รีเซ็ตรหัสผ่าน',
    'auth.backToLogin': 'กลับสู่หน้าเข้าสู่ระบบ',
    'auth.sendResetLink': 'ส่งลิงก์รีเซ็ต',
    'auth.emailSent': 'ส่งอีเมลแล้ว',
    'auth.emailSentMessage': 'อีเมลพร้อมคำแนะนำในการรีเซ็ตรหัสผ่านได้ถูกส่งไปยัง',
    'auth.checkInboxMessage': 'กรุณาตรวจสอบกล่องข้อความของคุณ หากคุณไม่ได้รับอีเมลภายในไม่กี่นาที กรุณาตรวจสอบในโฟลเดอร์สแปมหรือขยะ',
    'auth.orContinueWith': 'หรือดำเนินการต่อด้วย',
    'auth.continue': 'ดำเนินการต่อ',
    'auth.sendingOTP': 'กำลังส่ง OTP...',
    'auth.verifyOTP': 'ยืนยัน OTP',
    'auth.otpSubtitle': 'กรอกรหัสยืนยันที่ส่งไปยังอีเมลของคุณ',
    'auth.otpSentTo': 'รหัส OTP ได้ถูกส่งไปยัง',
    'auth.enterOTP': 'กรอกรหัส OTP',
    'auth.verify': 'ยืนยัน',
    'auth.verifying': 'กำลังยืนยัน...',
    'auth.didntReceiveOTP': 'ยังไม่ได้รับรหัส?',
    'auth.resendOTP': 'ส่งรหัสอีกครั้ง',
    'auth.resendOTPIn': 'ส่งอีกครั้งใน',
    'auth.changeEmail': 'เปลี่ยนอีเมล',
    'auth.otpResent': 'ส่ง OTP อีกครั้งแล้ว',
    'auth.otpResentMessage': 'รหัส OTP ใหม่ได้ถูกส่งไปยังอีเมลของคุณแล้ว',
    'auth.emailPlaceholder': 'กรอกที่อยู่อีเมลของคุณ',
    // Error messages
    'auth.errors.emailRequired': 'จำเป็นต้องใส่อีเมลหรือเบอร์โทร',
    'auth.errors.passwordMin': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'auth.errors.emailInvalid': 'กรุณากรอกอีเมลที่ถูกต้อง',
    'auth.errors.otpInvalid': 'กรุณากรอกรหัส OTP 6 หลักที่ถูกต้อง',
    'auth.errors.titleRequired': 'จำเป็นต้องเลือกคำนำหน้า',
    'auth.errors.firstNameRequired': 'จำเป็นต้องใส่ชื่อ',
    'auth.errors.lastNameRequired': 'จำเป็นต้องใส่นามสกุล',
    'auth.errors.phoneRequired': 'จำเป็นต้องใส่เบอร์โทร',
    'auth.errors.passwordRequired': 'จำเป็นต้องใส่รหัสผ่าน',
    'auth.errors.passwordConfirmRequired': 'กรุณายืนยันรหัสผ่าน',
    'auth.errors.passwordMismatch': 'รหัสผ่านไม่ตรงกัน',
    'auth.errors.emailMismatch': 'อีเมลไม่ตรงกัน',
    'auth.errors.agreeTermsRequired': 'คุณต้องยอมรับข้อกำหนดและเงื่อนไข',
    'auth.errors.agreePDPARequired': 'คุณต้องยอมรับนโยบายความเป็นส่วนตัว',
    'auth.errors.passportIdRequired': 'กรุณากรอกเลขบัตรประชาชน/พาสปอร์ต',
    'auth.errors.nicknameRequired': 'กรุณากรอกชื่อเล่น',
    // Dropdown options
    'auth.titles.mr': 'นาย',
    'auth.titles.mrs': 'นาง',
    'auth.titles.ms': 'นางสาว',
    'auth.titles.dr': 'ดร.',
    'auth.titles.prof': 'ศ.',
    'auth.grades.kindergarten': 'อนุบาล',
    'auth.grades.grade1': 'ประถม 1',
    'auth.grades.grade2': 'ประถม 2',
    'auth.grades.grade3': 'ประถม 3',
    'auth.grades.grade4': 'ประถม 4',
    'auth.grades.grade5': 'ประถม 5',
    'auth.grades.grade6': 'ประถม 6',
    'auth.grades.grade7': 'มัธยม 1',
    'auth.grades.grade8': 'มัธยม 2',
    'auth.grades.grade9': 'มัธยม 3',
    'auth.grades.grade10': 'มัธยม 4',
    'auth.grades.grade11': 'มัธยม 5',
    'auth.grades.grade12': 'มัธยม 6',
    'auth.acceptTerms': 'ฉันยอมรับ',
    'auth.and': 'และ',
    'auth.termsOfService': 'ข้อกำหนดการใช้บริการ',
    'auth.privacyPolicy': 'นโยบายความเป็นส่วนตัว',
    'auth.signupTitle': 'สมัครสมาชิก',
    'auth.signupSubtitle': 'เริ่มต้นการใช้งานเพียงไม่กี่ขั้นตอน',
    'auth.step1': 'ข้อมูลผู้ปกครอง',
    'auth.step2': 'ข้อมูลบุตร',
    'auth.addChild': 'เพิ่มบุตร',
    'auth.child': 'บุตรคนที่',
    'auth.grade': 'ชั้นเรียน',
    'auth.selectGrade': 'เลือกชั้นเรียน',
    'auth.campus': 'วิทยาเขต',
    'auth.selectCampus': 'เลือกวิทยาเขต',
    'auth.passportId': 'เลขบัตรประชาชน/พาสปอร์ต',
    'auth.passportIdPlaceholder': 'กรอกเลขบัตรประชาชนหรือพาสปอร์ต',
    'auth.confirmEmail': 'ยืนยันอีเมล',
    'auth.confirmEmailPlaceholder': 'กรอกอีเมลอีกครั้ง',
    'auth.wechatLineId': 'WeChat/Line ID (ถ้ามี)',
    'auth.wechatLineIdPlaceholder': 'กรอก WeChat ID หรือ Line ID',
    'auth.agentName': 'ชื่อตัวแทน (ถ้ามี)',
    'auth.agentNamePlaceholder': 'กรอกชื่อตัวแทน',
    'auth.nickname': 'ชื่อเล่น',
    'auth.nicknamePlaceholder': 'กรอกชื่อเล่น',
    
    // Portal
    'portal.title': 'พอร์ทัลผู้ปกครอง',
    'portal.welcome': 'ยินดีต้อนรับ',
    'portal.loginTitle': 'เข้าสู่ระบบ',
    'portal.loginSubtitle': 'ยินดีต้อนรับสู่พอร์ทัลผู้ปกครอง',
    'portal.today': 'วันนี้',
    'portal.notifications': 'การแจ้งเตือน',
    'portal.tuitionPayment': 'ค่าเล่าเรียน',
    'portal.extraActivities': 'กิจกรรมพิเศษ',
    'portal.others': 'อื่นๆ',
    'portal.selectStudent': 'เลือกนักเรียน',
    'portal.viewAllChildren': 'ดูบุตรทั้งหมด',
    'portal.dashboard': 'แดชบอร์ด',
    'portal.tuition': 'ค่าเล่าเรียน',
    'portal.afterSchool': 'หลังเลิกเรียน',
    'portal.summer': 'กิจกรรมฤดูร้อน',
    'portal.receipts': 'ใบเสร็จ',
    'portal.outstandingInvoices': 'ใบแจ้งหนี้ค้างชำระ',
    'portal.paidThisTerm': 'ชำระแล้วภาคเรียนนี้',
    'portal.creditBalance': 'ยอดเครดิต',
    'portal.availableCourses': 'คอร์สที่เปิดรับ',
    'portal.upcomingDeadlines': 'กำหนดการที่ใกล้มาถึง',
    'portal.importantDates': 'วันสำคัญและการเตือนสำหรับ',
    'portal.pending': 'รอชำระ',
    'portal.completedPayments': 'การชำระเงินที่สำเร็จ',
    'portal.availableCredit': 'เครดิตที่ใช้ได้',
    'portal.coursesWithSpots': 'คอร์สที่ยังมีที่ว่าง',
    'portal.due': 'ครบกำหนด',
     'portal.cart': 'ตะกร้า',
      'portal.items': 'รายการ',
     'portal.proceedToCheckout': 'ดำเนินการชำระเงิน',
     'portal.cartEmpty': 'ตะกร้าของคุณว่างเปล่า',
     'portal.backToActivities': 'กลับไปยังกิจกรรม',
     'portal.subtotal': 'รวมย่อย',
     'portal.parentAccount': 'บัญชีผู้ปกครอง',
     'portal.accountSettings': 'ตั้งค่าบัญชี',
     'portal.paymentMethods': 'วิธีการชำระเงิน',
     'portal.notificationSettings': 'ตั้งค่าการแจ้งเตือน',
     'portal.allStudents': 'นักเรียนทุกคน',
     'portal.studentFilter': 'กรองตามนักเรียน',
     'portal.addItemsToCart': 'เพิ่มคอร์สหรือกิจกรรมเพื่อเริ่มต้น',
     'portal.selectAll': 'เลือกทั้งหมด',
     'portal.selectedItems': 'รายการที่เลือก',
     'portal.itemsSelected': 'รายการที่เลือก',
     'portal.priceDetails': 'รายละเอียดราคา',
     'portal.total': 'รวมทั้งหมด',
     'portal.cartStep': 'ตะกร้า',
     'portal.paymentStep': 'ชำระเงิน',
     'portal.receiveStep': 'เสร็จสิ้น',
     'portal.backToDashboard': 'กลับสู่แดชบอร์ด',
     'portal.course': 'คอร์ส',
     'portal.noReceipts': 'ไม่มีใบเสร็จ',
     'portal.downloadReceipt': 'ดาวน์โหลดใบเสร็จ',
     'portal.courseSelected': 'คอร์สที่เลือกสำหรับลงทะเบียน',
     'portal.activity': 'กิจกรรม',
     'portal.addedToCart': 'เพิ่มลงตะกร้าแล้ว',
     'portal.removedFromCart': 'ลบออกจากตะกร้าแล้ว',
     'portal.tuitionFees': 'ค่าเล่าเรียน',
     'portal.checkout': 'ชำระเงิน',
     'portal.vendor': 'ผู้จัดกิจกรรม',
    'portal.tuitionStatus': 'สถานะค่าเล่าเรียน',
    'portal.afterSchoolActivities': 'กิจกรรมหลังเลิกเรียน',
    'portal.summerActivities': 'กิจกรรมฤดูร้อน',
    'portal.academicYear': 'ปีการศึกษา 2567-2568',
    'portal.paid': 'ชำระแล้ว',
    'portal.pendingStatus': 'รอชำระ',
    'portal.noInvoice': 'ไม่มีใบแจ้งหนี้',
    'portal.enrolled': 'ลงทะเบียนแล้ว',
     'portal.noAfterSchoolEnrolled': 'ยังไม่ได้ลงทะเบียนกิจกรรมหลังเลิกเรียน',
     'portal.noSummerEnrolled': 'ยังไม่ได้ลงทะเบียนกิจกรรมฤดูร้อน',
     'portal.fullyBooked': 'เต็มแล้ว',
     'portal.spotsLeft': 'ที่เหลือ',
     'portal.spotsAvailable': 'ที่ว่าง',
     'portal.capacity': 'ความจุ',
     'portal.scheduleConflict': 'ตารางเวลาขัดแย้งกับคอร์สอื่น',
     'portal.addToCart': 'เพิ่มลงตะกร้า',
     'portal.removeFromCart': 'ลบออกจากตะกร้า',
     'portal.receiptName': 'ชื่อใบเสร็จ',
     'portal.dateOfPurchase': 'วันที่ซื้อ',
     'portal.amount': 'จำนวนเงิน',
     'portal.category': 'ประเภท',
       'portal.student': 'นักเรียน',
       
       // Cart
       'cart.timeRemaining': 'เวลาที่เหลือ',
     
     // Course translations
     'course.course-001.name': 'หลักสูตรหุ่นยนต์และวิศวกรรม',
     'course.course-001.description': 'เรียนรู้พื้นฐานหุ่นยนต์และวิศวกรรม',
     'course.course-002.name': 'คณิตศาสตร์ขั้นสูง',
     'course.course-002.description': 'เรียนรู้แนวคิดทางคณิตศาสตร์ที่ซับซ้อน',
     'course.course-003.name': 'การเขียนสร้างสรรค์',
     'course.course-003.description': 'แสดงออกความคิดสร้างสรรค์ผ่านการเล่าเรื่องและบทกวี',
     'course.course-004.name': 'ภาษาต่างประเทศ (สเปน)',
     'course.course-004.description': 'เชี่ยวชาญทักษะการสื่อสารภาษาสเปน',
     'course.course-005.name': 'ศิลปะและการออกแบบ',
     'course.course-005.description': 'สำรวจการแสดงออกทางศิลปะผ่านสื่อต่าง ๆ',
     'course.summer-001.name': 'ค่ายหุ่นยนต์และวิศวกรรม',
     'course.summer-001.description': 'การเรียนรู้ STEM แบบลงมือปฏิบัติ',
     'course.summer-002.name': 'เวิร์คช็อปศิลปะและหัตถกรรม',
     'course.summer-002.description': 'แสดงออกความคิดสร้างสรรค์ผ่านสื่อศิลปะต่าง ๆ',
      'course.summer-003.name': 'สถาบันฝึกทักษะฟุตบอล',
      'course.summer-003.description': 'พัฒนาเทคนิคฟุตบอลและการทำงานเป็นทีม',
     
     // Payment methods  
     'payment.creditCard': 'บัตรเครดิต',
     'payment.bankTransfer': 'โอนเงินผ่านธนาคาร',
     'payment.creditNote': 'เครดิตโน้ต',
     'payment.cash': 'เงินสด',
     'payment.promptPay': 'พร้อมเพย์', 
     'payment.wechatPay': 'WeChat Pay',
     'payment.alipay': 'Alipay',
     'payment.bankAccount': 'บัญชีธนาคาร',
    // Portal - Payment
    'portal.paymentOptions': 'ตัวเลือกการชำระเงิน',
    'portal.paymentPeriod': 'ระยะเวลาการชำระ',
    'portal.termly': 'รายเทอม',
    'portal.yearly': 'รายปี (ประหยัด 10%)',
    'portal.applyCreditNote': 'ใช้เครดิตโน้ต',
    'portal.useCreditNote': 'ใช้เครดิตโน้ต',
    'portal.available': 'มีในระบบ',
    'portal.paymentMethod': 'วิธีการชำระเงิน',
    'portal.free': 'ฟรี',
    'portal.paymentSummary': 'สรุปการชำระเงิน',
    'portal.tuitionFee': 'ค่าเล่าเรียน',
    'portal.creditNoteApplied': 'ใช้เครดิตโน้ตแล้ว',
    'portal.paymentFee': 'ค่าธรรมเนียมการชำระ',
    'portal.totalAmount': 'จำนวนเงินรวม',
    'portal.cancel': 'ยกเลิก',
    'portal.pay': 'ชำระเงิน',
    'portal.payNow': 'ชำระเงิน',
    'portal.applyCreditPay': 'ใช้เครดิตและชำระ',
    
    // Invoice Status
    'invoice.pending': 'รอชำระ',
    'invoice.overdue': 'เกินกำหนด',
    'invoice.paid': 'ชำระแล้ว',
    'invoice.partial': 'ชำระบางส่วน',
    'invoice.due': 'ครบกำหนด',
    'invoice.amountDue': 'จำนวนเงินที่ต้องชำระ',
    'invoice.availableCredit': 'เครดิตที่มีอยู่',
    'invoice.canPayWithCredit': 'สามารถชำระด้วยเครดิตที่มีอยู่ได้',
    
    // Payment Success
    'payment.success': 'ชำระเงินสำเร็จ',
    'payment.successMessage': 'การชำระค่าเทอมของ {studentName} เรียบร้อยแล้ว',
    'payment.paymentDetails': 'รายละเอียดการชำระเงิน',
    'payment.receiptNumber': 'หมายเลขใบเสร็จ',
    'payment.amount': 'จำนวนเงิน',
    'payment.paymentDate': 'วันที่ชำระ',
    'payment.paymentMethod': 'วิธีชำระเงิน',
    'payment.paymentType': 'ประเภทการชำระ',
    'payment.downloadReceipt': 'ดาวน์โหลดใบเสร็จ PDF',
    'payment.downloadStarted': 'กำลังเตรียมไฟล์ PDF ใบเสร็จ',
    'payment.backToMain': 'กลับสู่หน้าหลัก',
    'payment.emailNotification': 'ใบเสร็จจะถูกส่งไปยังอีเมลที่ลงทะเบียนไว้ภายใน 5-10 นาที',
    
    // Common
    'common.submit': 'ส่ง',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.edit': 'แก้ไข',
    'common.delete': 'ลบ',
    'common.close': 'ปิด',
    'common.back': 'กลับ',
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.step': 'ขั้นตอนที่',
    'common.of': 'จาก',
    
    // Days
    'day.monday': 'จันทร์',
    'day.tuesday': 'อังคาร',
    'day.wednesday': 'พุธ',
    'day.thursday': 'พฤหัสบดี',
    'day.friday': 'ศุกร์',
    'day.saturday': 'เสาร์',
    'day.sunday': 'อาทิตย์',
    
    // Months
    'month.january': 'มกราคม',
    'month.february': 'กุมภาพันธ์',
    'month.march': 'มีนาคม',
    'month.april': 'เมษายน',
    'month.may': 'พฤษภาคม',
    'month.june': 'มิถุนายน',
    'month.july': 'กรกฎาคม',
    'month.august': 'สิงหาคม',
    'month.september': 'กันยายน',
    'month.october': 'ตุลาคม',
    'month.november': 'พฤศจิกายน',
    'month.december': 'ธันวาคม',
    
    // Exam
    'portal.exam': 'การสอบ',
    'exam.registration': 'ลงทะเบียนสอบ',
    'exam.register': 'ลงทะเบียน',
    'exam.registered': 'ลงทะเบียนสอบแล้ว',
    'exam.passportId': 'หมายเลขหนังสือเดินทาง/บัตรประชาชน',
    'exam.passportIdPlaceholder': 'กรอกหมายเลขหนังสือเดินทางหรือบัตรประชาชน',
    'exam.photoUpload': 'รูปถ่าย',
    'exam.clickToUpload': 'คลิกเพื่ออัปโหลดรูปภาพ',
    'exam.grade': 'ระดับชั้น',
    'exam.selectGrade': 'เลือกระดับชั้น',
    'exam.gender': 'เพศ',
    'exam.male': 'ชาย',
    'exam.female': 'หญิง',
    'exam.age': 'อายุ',
    'exam.agePlaceholder': 'กรอกอายุ',
    'exam.selectOption': 'เลือกตัวเลือกการสอบ',
    'exam.examOnly': 'สอบอย่างเดียว',
    'exam.examWithDelivery': 'สอบ + จัดส่งผลสอบ',
    'exam.deliveryOption': 'จัดส่งผลสอบ',
    'exam.errors.passportRequired': 'กรุณากรอกหมายเลขหนังสือเดินทาง/บัตรประชาชน',
    'exam.errors.photoRequired': 'กรุณาอัปโหลดรูปถ่าย',
    'exam.errors.gradeRequired': 'กรุณาเลือกระดับชั้น',
    'exam.errors.genderRequired': 'กรุณาเลือกเพศ',
    'exam.errors.ageRequired': 'กรุณากรอกอายุที่ถูกต้อง (1-25)',
    
    // Transaction History & Credit Note
    'portal.transactionHistory': 'ประวัติธุรกรรม',
    'creditNote.title': 'ใบลดหนี้',
    'creditNote.history': 'ประวัติใบลดหนี้',
    'creditNote.availableCredit': 'เครดิตคงเหลือ',
    'creditNote.usedCredit': 'เครดิตที่ใช้ไป',
    'creditNote.perStudentNote': 'ใบลดหนี้เป็นของนักเรียนแต่ละคนและไม่สามารถใช้ข้ามนักเรียนได้',
    'creditNote.filters': 'ตัวกรอง',
    'creditNote.searchPlaceholder': 'ค้นหาใบลดหนี้ (รหัส, รายละเอียด)...',
    'creditNote.academicYear': 'ปีการศึกษา',
    'creditNote.allYears': 'ทุกปี',
    'creditNote.type': 'ประเภท',
    'creditNote.allTypes': 'ทั้งหมด',
    'creditNote.active': 'ใช้งานได้',
    'creditNote.used': 'ใช้แล้ว',
    'creditNote.expired': 'หมดอายุ',
    'creditNote.issued': 'วันที่ออก',
    'creditNote.noResults': 'ไม่พบใบลดหนี้',
    'creditNote.typeRefund': 'คืนเงิน',
    'creditNote.typeDiscount': 'ส่วนลด',
    'creditNote.typeOverpayment': 'ชำระเกิน',
    'creditNote.typeCancellation': 'ยกเลิก',
    
    // Receipt filters and timeline
    'receipt.month': 'เดือน',
    'receipt.pickMonth': 'เลือกเดือน',
    'receipt.clearMonth': 'ล้าง',
    'receipt.student': 'นักเรียน',
    'receipt.allStudents': 'ทุกคน',
    'receipt.type': 'ประเภท',
    'receipt.allTypes': 'ทั้งหมด',
    'receipt.typeTuition': 'ค่าเล่าเรียน',
    'receipt.typeActivity': 'กิจกรรม',
    'receipt.typeCamp': 'ค่าย',
    'receipt.typeEvent': 'กิจกรรมพิเศษ',
    'receipt.typeExam': 'การสอบ',
    'receipt.showing': 'แสดง',
    'receipt.of': 'จาก',
    'receipt.transactionTimeline': 'ไทม์ไลน์ธุรกรรม',
    'receipt.usedCreditNote': 'ใช้ใบลดหนี้',
    'receipt.appliedTo': 'นำไปใช้กับ',
    'receipt.noCreditNotesUsed': 'ไม่มีใบลดหนี้ที่ใช้ในธุรกรรมนี้',
    
    // Event submenu
    'portal.eventExam': 'สอบ',
    'portal.eventTrip': 'ทัศนศึกษา',
    'portal.eventCarnival': 'งานคาร์นิวัลและคอนเสิร์ต',
    
    // Trip
    'trip.acceptTrip': 'ยืนยันเข้าร่วม',
    'trip.declineTrip': 'ไม่เข้าร่วม',
    'trip.proceedToPayment': 'ดำเนินการชำระเงิน',
    'trip.changeDecision': 'เปลี่ยนการตัดสินใจ',
    'trip.notAttending': 'ไม่ได้เข้าร่วม',
    'trip.accepted': 'ยอมรับแล้ว',
    'trip.paid': 'ชำระแล้ว',
    'trip.paymentDeadline': 'กำหนดชำระเงิน',
    'trip.tripDetails': 'รายละเอียดทัศนศึกษา',
    'trip.deadlinePassed': 'เลยกำหนดแล้ว',
    'trip.paymentConfirmed': 'ยืนยันการชำระเงินแล้ว',
    'trip.searchTrips': 'ค้นหาทัศนศึกษา...',
    'trip.noTripsFound': 'ไม่พบทัศนศึกษา',
    
    // Carnival
    'carnival.comingSoon': 'เร็วๆ นี้',
    'carnival.stayTuned': 'รอติดตามกิจกรรมที่กำลังจะมาถึง',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.contact': '联系我们',
    'nav.login': '登录',
    'nav.signup': '注册',
    'nav.logout': '退出',
    
    // Authentication
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.forgotPassword': '忘记密码',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.fullName': '姓名',
    'auth.phoneNumber': '电话号码',
    'auth.title': '称谓',
    'auth.selectTitle': '选择称谓',
    'auth.firstName': '名字',
    'auth.lastName': '姓氏',
    'auth.nextChildrenInfo': '下一步：子女信息',
    'auth.rememberMe': '记住我',
    'auth.noAccount': '没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.signInHere': '在此登录',
    'auth.signUpHere': '在此注册',
    'auth.resetPassword': '重置密码',
    'auth.resetPasswordTitle': '重置密码',
    'auth.resetPasswordSubtitle': '请输入您注册时使用的邮箱以接收密码重置链接',
    'auth.backToLogin': '返回登录',
    'auth.sendResetLink': '发送重置链接',
    'auth.emailSent': '邮件已发送',
    'auth.emailSentMessage': '包含重置密码说明的邮件已发送至',
    'auth.checkInboxMessage': '请检查您的收件箱，如果几分钟内没有收到邮件，请检查垃圾邮件或垃圾文件夹。',
    'auth.orContinueWith': '或继续使用',
    // Error messages
    'auth.errors.emailRequired': '需要输入邮箱或电话号码',
    'auth.errors.passwordMin': '密码至少需要6个字符',
    'auth.errors.emailInvalid': '请输入有效的邮箱地址',
    'auth.errors.titleRequired': '需要选择称谓',
    'auth.errors.firstNameRequired': '需要输入名字',
    'auth.errors.lastNameRequired': '需要输入姓氏',
    'auth.errors.phoneRequired': '需要输入电话号码',
    'auth.errors.passwordRequired': '需要输入密码',
    'auth.errors.passwordConfirmRequired': '请确认密码',
    'auth.errors.passwordMismatch': '密码不匹配',
    'auth.errors.emailMismatch': '邮箱不匹配',
    'auth.errors.agreeTermsRequired': '您必须同意条款和条件',
    'auth.errors.agreePDPARequired': '您必须同意隐私政策',
    'auth.errors.passportIdRequired': '请输入身份证/护照号码',
    'auth.errors.nicknameRequired': '请输入昵称',
    // Dropdown options
    'auth.titles.mr': '先生',
    'auth.titles.mrs': '夫人',
    'auth.titles.ms': '女士',
    'auth.titles.dr': '博士',
    'auth.titles.prof': '教授',
    'auth.grades.kindergarten': '幼儿园',
    'auth.grades.grade1': '一年级',
    'auth.grades.grade2': '二年级',
    'auth.grades.grade3': '三年级',
    'auth.grades.grade4': '四年级',
    'auth.grades.grade5': '五年级',
    'auth.grades.grade6': '六年级',
    'auth.grades.grade7': '七年级',
    'auth.grades.grade8': '八年级',
    'auth.grades.grade9': '九年级',
    'auth.grades.grade10': '十年级',
    'auth.grades.grade11': '十一年级',
    'auth.grades.grade12': '十二年级',
    'auth.acceptTerms': '我接受',
    'auth.and': '和',
    'auth.termsOfService': '服务条款',
    'auth.privacyPolicy': '隐私政策',
    'auth.signupTitle': '注册',
    'auth.signupSubtitle': '只需几个步骤即可开始',
    'auth.step1': '家长信息',
    'auth.step2': '子女信息',
    'auth.addChild': '添加子女',
    'auth.child': '子女',
    'auth.grade': '年级',
    'auth.selectGrade': '选择年级',
    'auth.campus': '校区',
    'auth.selectCampus': '选择校区',
    'auth.passportId': '身份证/护照号码',
    'auth.passportIdPlaceholder': '输入身份证或护照号码',
    'auth.confirmEmail': '确认邮箱',
    'auth.confirmEmailPlaceholder': '再次输入您的邮箱地址',
    'auth.wechatLineId': '微信/Line ID（可选）',
    'auth.wechatLineIdPlaceholder': '输入微信ID或Line ID',
    'auth.agentName': '代理人姓名（如有）',
    'auth.agentNamePlaceholder': '输入代理人姓名',
    'auth.nickname': '昵称',
    'auth.nicknamePlaceholder': '输入昵称',
    
    // Portal
    'portal.title': '家长门户',
    'portal.welcome': '欢迎',
    'portal.loginTitle': '登录',
    'portal.loginSubtitle': '欢迎来到家长门户',
    'portal.today': '今天',
    'portal.notifications': '通知',
    'portal.tuitionPayment': '学费支付',
    'portal.extraActivities': '课外活动',
    'portal.others': '其他',
    'portal.selectStudent': '选择学生',
    'portal.viewAllChildren': '查看所有子女',
    'portal.dashboard': '仪表盘',
    'portal.tuition': '学费',
    'portal.afterSchool': '课后活动',
    'portal.summer': '夏令营',
    'portal.receipts': '收据',
    'portal.outstandingInvoices': '未付账单',
    'portal.paidThisTerm': '本学期已付',
    'portal.creditBalance': '信用余额',
    'portal.availableCourses': '可选课程',
    'portal.upcomingDeadlines': '即将到期',
    'portal.importantDates': '重要日期和提醒',
    'portal.pending': '待付',
    'portal.completedPayments': '已完成付款',
    'portal.availableCredit': '可用信用额度',
    'portal.coursesWithSpots': '有名额的课程',
    'portal.due': '截止日期',
     'portal.cart': '购物车',
      'portal.items': '项目',
       'portal.courseSelected': '选择注册的课程',
       'portal.activitySelected': '选择注册的活动',
     'portal.proceedToCheckout': '进行结账',
     'portal.cartEmpty': '您的购物车是空的',
     'portal.backToActivities': '返回活动',
     'portal.subtotal': '小计',
     'portal.parentAccount': '家长账户',
     'portal.accountSettings': '账户设置',
     'portal.paymentMethods': '付款方式',
     'portal.notificationSettings': '通知设置',
     'portal.allStudents': '所有学生',
     'portal.studentFilter': '按学生筛选',
     'portal.addItemsToCart': '添加一些课程或活动开始',
     'portal.selectAll': '全选',
     'portal.selectedItems': '已选项目',
     'portal.itemsSelected': '项目已选择',
     'portal.priceDetails': '价格详情',
     'portal.total': '总计',
     'portal.cartStep': '购物车',
     'portal.paymentStep': '付款',
     'portal.receiveStep': '完成',
     'portal.backToDashboard': '返回仪表板',
     'portal.course': '课程',
     'portal.noReceipts': '没有收据可用',
     'portal.downloadReceipt': '下载收据',
     'portal.activity': '活动',
     'portal.addedToCart': '已添加到购物车',
     'portal.removedFromCart': '已从购物车中移除',
     'portal.tuitionFees': '学费',
     'portal.checkout': '结算',
     'portal.vendor': '供应商',
    'portal.tuitionStatus': '学费状态',
    'portal.afterSchoolActivities': '课后活动',
    'portal.summerActivities': '夏令营活动',
    'portal.academicYear': '学年 2024-2025',
    'portal.paid': '已付',
    'portal.pendingStatus': '待付',
    'portal.noInvoice': '无账单',
    'portal.enrolled': '已注册',
     'portal.noAfterSchoolEnrolled': '未注册课后活动',
     'portal.noSummerEnrolled': '未注册夏令营活动',
     'portal.fullyBooked': '已满',
     'portal.spotsLeft': '剩余名额',
     'portal.spotsAvailable': '可用名额',
     'portal.capacity': '容量',
     'portal.scheduleConflict': '与现有课程时间冲突',
     'portal.addToCart': '加入购物车',
     'portal.removeFromCart': '从购物车移除',
     'portal.receiptName': '收据名称',
     'portal.dateOfPurchase': '购买日期',
     'portal.amount': '金额',
     'portal.category': '类别',
      'portal.student': '学生',
      
      // Cart
      'cart.timeRemaining': '剩余时间',
     
     // Course translations
     'course.course-001.name': '机器人工程',
     'course.course-001.description': '学习机器人和工程基础',
     'course.course-002.name': '高级数学',
     'course.course-002.description': '掌握复杂的数学概念',
     'course.course-003.name': '创意写作',
     'course.course-003.description': '通过讲故事和诗歌表达创意',
     'course.course-004.name': '外语（西班牙语）',
     'course.course-004.description': '掌握西班牙语交流技能',
     'course.course-005.name': '艺术与设计',
     'course.course-005.description': '通过各种媒体探索艺术表达',
     'course.summer-001.name': '机器人与工程营',
     'course.summer-001.description': '实践STEM学习体验',
     'course.summer-002.name': '艺术与手工作坊',
     'course.summer-002.description': '通过各种艺术媒体表达创意',
      'course.summer-003.name': '足球技能学院',
      'course.summer-003.description': '提高足球技术和团队合作',
     
     // Payment methods
     'payment.creditCard': '信用卡',
     'payment.bankTransfer': '银行转账',
     'payment.creditNote': '信用票据',
     'payment.cash': '现金',
     'payment.promptPay': 'PromptPay', 
     'payment.wechatPay': '微信支付',
     'payment.alipay': '支付宝',
     'payment.bankAccount': '银行账户',
     'portal.childrenOverviewTitle': '子女概况与注册状态',
    
    // Portal - Payment
    'portal.paymentOptions': '付款选项',
    'portal.paymentPeriod': '付款周期',
    'portal.termly': '学期付款',
    'portal.yearly': '年付 (节省 10%)',
    'portal.applyCreditNote': '使用信用票据',
    'portal.useCreditNote': '使用信用票据',
    'portal.available': '可用',
    'portal.paymentMethod': '付款方式',
    'portal.free': '免费',
    'portal.paymentSummary': '付款摘要',
    'portal.tuitionFee': '学费',
    'portal.creditNoteApplied': '已使用信用票据',
    'portal.paymentFee': '手续费',
    'portal.totalAmount': '总金额',
    'portal.cancel': '取消',
    'portal.pay': '付款',
    'portal.payNow': '付款',
    'portal.applyCreditPay': '使用信用并付款',
    
    // Invoice Status
    'invoice.pending': '待付款',
    'invoice.overdue': '逾期',
    'invoice.paid': '已付款',
    'invoice.partial': '部分付款',
    'invoice.due': '到期',
    'invoice.amountDue': '应付金额',
    'invoice.availableCredit': '可用信用',
    'invoice.canPayWithCredit': '可以使用现有信用付款',
    
    // Payment Success
    'payment.success': '支付成功',
    'payment.successMessage': '{studentName} 的学费支付已成功完成',
    'payment.paymentDetails': '支付详情',
    'payment.receiptNumber': '收据号码',
    'payment.amount': '金额',
    'payment.paymentDate': '支付日期',
    'payment.paymentMethod': '支付方式',
    'payment.paymentType': '支付类型',
    'payment.downloadReceipt': '下载收据 PDF',
    'payment.downloadStarted': '收据PDF下载即将开始',
    'payment.backToMain': '返回主页',
    'payment.emailNotification': '收据将在 5-10 分钟内发送到您注册的邮箱',
    
    // Progress
    'progress.cart': '购物车',
    'progress.payment': '支付',
    'progress.success': '完成',
    
    // Payment Processing
    'processing.selectPayment': '选择支付方式',
    'processing.confirmPayment': '确认支付',
    'processing.processing': '处理中...',
    'processing.success': '支付成功！',
    'processing.failed': '支付失败',
    'processing.timeout': '支付超时，请重试',
    'processing.scanQR': '扫描二维码支付',
    'processing.timeRemaining': '剩余时间',
    'processing.bankDetails': '银行账户详情',
    'processing.accountNumber': '账号',
    'processing.accountName': '账户名',
    'processing.bank': '银行',
    'processing.amount': '金额',
    'processing.back': '返回',
    'processing.tryAgain': '重试',
    'processing.cancel': '取消',
    'processing.redirecting': '正在跳转到银行...',
    'processing.checkingPayment': '正在检查支付...',
    'processing.generatingReceipt': '正在生成收据...',
    
    // Payment Success
    'success.paymentComplete': '支付成功',
    'success.registrationComplete': '注册完成',
    'success.activitiesRegistered': '已注册活动',
    'success.paymentDetails': '支付详情',
    'success.receiptNumber': '收据号码',
    'success.paymentAmount': '金额',
    'success.paymentDate': '支付日期',
    'success.paymentMethod': '支付方式',
    'success.downloadPDF': '下载收据PDF',
    'success.backToMain': '返回主页',
    'success.emailConfirmation': '收据和注册详情将在5-10分钟内发送到您注册的邮箱',
    
    // Common
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.close': '关闭',
    'common.back': '返回',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.step': '第',
    'common.of': '步，共',
    
    // Days
    'day.monday': '星期一',
    'day.tuesday': '星期二',
    'day.wednesday': '星期三',
    'day.thursday': '星期四',
    'day.friday': '星期五',
    'day.saturday': '星期六',
    'day.sunday': '星期日',
    
    // Months
    'month.january': '一月',
    'month.february': '二月',
    'month.march': '三月',
    'month.april': '四月',
    'month.may': '五月',
    'month.june': '六月',
    'month.july': '七月',
    'month.august': '八月',
    'month.september': '九月',
    'month.october': '十月',
    'month.november': '十一月',
    'month.december': '十二月',
    
    // Exam
    'portal.exam': '考试',
    'exam.registration': '考试报名',
    'exam.register': '报名',
    'exam.registered': '已报名考试',
    'exam.passportId': '护照/身份证号码',
    'exam.passportIdPlaceholder': '输入护照或身份证号码',
    'exam.photoUpload': '照片',
    'exam.clickToUpload': '点击上传照片',
    'exam.grade': '年级',
    'exam.selectGrade': '选择年级',
    'exam.gender': '性别',
    'exam.male': '男',
    'exam.female': '女',
    'exam.age': '年龄',
    'exam.agePlaceholder': '输入年龄',
    'exam.selectOption': '选择考试选项',
    'exam.examOnly': '仅考试',
    'exam.examWithDelivery': '考试 + 成绩寄送',
    'exam.deliveryOption': '成绩寄送',
    'exam.errors.passportRequired': '需要护照/身份证号码',
    'exam.errors.photoRequired': '需要上传照片',
    'exam.errors.gradeRequired': '需要选择年级',
    'exam.errors.genderRequired': '需要选择性别',
    'exam.errors.ageRequired': '需要有效年龄 (1-25)',
    
    // Transaction History & Credit Note
    'portal.transactionHistory': '交易历史',
    'creditNote.title': '贷记单',
    'creditNote.history': '贷记单历史',
    'creditNote.availableCredit': '可用额度',
    'creditNote.usedCredit': '已用额度',
    'creditNote.perStudentNote': '贷记单仅限于单个学生，不能跨学生使用',
    'creditNote.filters': '筛选',
    'creditNote.searchPlaceholder': '搜索贷记单 (编号, 详情)...',
    'creditNote.academicYear': '学年',
    'creditNote.allYears': '所有年份',
    'creditNote.type': '类型',
    'creditNote.allTypes': '全部',
    'creditNote.active': '可用',
    'creditNote.used': '已使用',
    'creditNote.expired': '已过期',
    'creditNote.issued': '发放日期',
    'creditNote.noResults': '未找到贷记单',
    'creditNote.typeRefund': '退款',
    'creditNote.typeDiscount': '折扣',
    'creditNote.typeOverpayment': '超额支付',
    'creditNote.typeCancellation': '取消',
    
    // Receipt filters and timeline
    'receipt.month': '月份',
    'receipt.pickMonth': '选择月份',
    'receipt.clearMonth': '清除',
    'receipt.student': '学生',
    'receipt.allStudents': '全部学生',
    'receipt.type': '类型',
    'receipt.allTypes': '全部类型',
    'receipt.typeTuition': '学费',
    'receipt.typeActivity': '活动',
    'receipt.typeCamp': '营地',
    'receipt.typeEvent': '活动',
    'receipt.typeExam': '考试',
    'receipt.showing': '显示',
    'receipt.of': '共',
    'receipt.transactionTimeline': '交易时间线',
    'receipt.usedCreditNote': '使用贷记单',
    'receipt.appliedTo': '应用于',
    'receipt.noCreditNotesUsed': '此交易未使用贷记单',
    
    // Event submenu
    'portal.eventExam': '考试',
    'portal.eventTrip': '旅行',
    'portal.eventCarnival': '嘉年华和音乐会',
    
    // Trip
    'trip.acceptTrip': '接受行程',
    'trip.declineTrip': '拒绝行程',
    'trip.proceedToPayment': '继续付款',
    'trip.changeDecision': '更改决定',
    'trip.notAttending': '不参加',
    'trip.accepted': '已接受',
    'trip.paid': '已支付',
    'trip.paymentDeadline': '付款截止日期',
    'trip.tripDetails': '行程详情',
    'trip.deadlinePassed': '截止日期已过',
    'trip.paymentConfirmed': '付款已确认',
    'trip.searchTrips': '搜索旅行...',
    'trip.noTripsFound': '未找到旅行',
    
    // Carnival
    'carnival.comingSoon': '即将推出',
    'carnival.stayTuned': '敬请期待即将到来的活动',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const getFontClass = () => {
    switch (language) {
      case 'th':
        return 'font-sukhumvit';
      case 'zh':
        return 'font-noto-sc';
      default:
        return 'font-lato';
    }
  };

  const formatCurrency = (amount: number): string => {
    // Always use THB currency
    return new Intl.NumberFormat('th-TH', {
      style: 'currency',
      currency: 'THB'
    }).format(amount);
  };

  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getFontClass, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};